### ISSUE TITLE
Ask to official pdm to add your library and implementation

### ISSUE THREAD

**Issue by JeyDi** [znd4/pdm-dotenv#14]
Hi @znd4 congratulations on the excellent library, it works very well and is very useful especially for CI/CD pipelines.

I commented an [issue in the official PDM repository](https://github.com/pdm-project/pdm/issues/2513) asking for the implementation of the same functionality, citing you as a good example of implementation :)

**Comment by znd4** [comment]
Sorry, going to close this since the upstream issue was rejected. still open to merging into `pdm` if they change their mind.

Also, thanks for the kind words :)
