### ISSUE TITLE
Doesn't work with pdm build or pdm use

### ISSUE THREAD

**Issue by robtaylor** [znd4/pdm-dotenv#7]
The environment doesn't get set on `pdm build` or on entry to the venv. Is this fixable?

**Comment by znd4** [comment]
#8 should get `pdm build` or `pdm use` working. I'm curious about what you mean by "entry to the venv". If you mean `source path/to/venv/activate` or similar, I don't know of a way to support that (although I might be able to offer a recommendation if I knew more about the problem you want to solve)

**Comment by znd4** [comment]
Let me know if any of your issues persist after upgrading to `pdm-dotenv>=0.3.0`

**Comment by znd4** [comment]
Hi, just found out about `eval $(pdm venv activate)`. Unfortunately, there isn't a way for a pdm plugin to modify the code that gets output by that command.

The best option (if you want to be able to directly call cli tools like `pytest` without prepending with `pdm run`, your best bet is to use [direnv](direnv.net). It even supports [loading a .env file](https://direnv.net/man/direnv-stdlib.1.html#codedotenv-ltdotenvpathgtcode), so you don't need to move away from a `.env`-based workflow for existing projects.

Hopefully that helps!
